name: Test PowerShell on Ubuntu
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set working directory to root of repository
        run: echo "{name}={value}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Run Pester
        shell: pwsh
        run: |
          # Run Pester tests with Code Coverage
          $config = New-PesterConfiguration
          $config.Run.Path = "tests"
          $config.CodeCoverage.Enabled = $true
          $config.TestResult.Enabled = $true
          Invoke-Pester -Configuration $config
      
      - name: Upload code coverage report
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage.xml