name: Build and Test Module
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      - name: Upload artifact to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: path/to/artifact.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Install Dependencies
      #   shell: pwsh
      #   run: './install.ps1'

      # - name: Build
      #   shell: pwsh
      #   run: Invoke-Build Build

      # - name: Tests
      #   shell: pwsh
      #   run: Invoke-Build test -Output Normal

      # - name: Upload code coverage report
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: 'coverage.xml'

      # - name: Package Module
      #   run: Compress-Archive -Path output -DestinationPath quickpath.zip
      #   shell: pwsh
      
      # - name: Upload Module
      #   uses: actions/upload-artifact@main
        # with:
        #   name: 'quickpath'
        #   path: './'
