name: Build and Test Module
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set working directory to root of repository
        run: echo "{name}={value}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Install Invoke-Build
        shell: pwsh
        run: Install-Module -Name InvokeBuild -Scope CurrentUser -Force

      - name: Build
        shell: pwsh
        run: Invoke-Build Build

      # - name: Install Pester
      #   shell: pwsh
      #   run: Install-Module -Name Pester -Scope CurrentUser -Force
      # - name: Tests
      #   shell: pwsh
      #   run: Invoke-Build test -Output Normal
      # - name: Upload code coverage report
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: coverage.xml
        
      - name: Install NuGet CLI
        shell: pwsh
        run: Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe

      - name: Package Module into .nupkg
        shell: pwsh
        run: .\nuget.exe pack "./output/quickpath/quickpath.nuspec" -OutputDirectory .
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: powershell-module
          path: ./*.nupkg
