name: Test PowerShell on Ubuntu
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Invoke-Build
        shell: pwsh
        run: Install-Module -Name InvokeBuild -Scope CurrentUser -Force

      - name: Build
        shell: pwsh
        run: Invoke-Build Build

      - name: Install Pester
        shell: pwsh
        run: Install-Module -Name Pester -Scope CurrentUser -Force

      - name: Test
        shell: pwsh
        run: Invoke-Build Test

      - name: Run Pester
        run: |
          $config = New-PesterConfiguration
          $config.Run.Path = "."
          $config.CodeCoverage.Enabled = $true
          $config.TestResult.Enabled = $true
          Invoke-Pester -Configuration $config
      
      - name: Upload code coverage report
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage.xml