name: Publish Module

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        
      - name: Download artifact from release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest_release=$(gh release list --limit 1 --json tagName -q ".[0].tagName")
          gh release download $latest_release --pattern "artifact.zip" --dir ./downloaded

      - name: Display structure of downloaded files
        run: ls -R

      # - name: Extract package
      #   run: Expand-Archive -Path quickpath.zip -DestinationPath .
        
      # - name: Override module version
      #   run: |
      #     $tag = "${{ github.event.release.tag_name }}"
      #     (Get-Content -Path 'quickpath/quickpath.psd1') -replace 'Version = ''[0-9\.]+''', "Version = '$tag'" | Set-Content -Path 'quickpath/quickpath.psd1'
      #   shell: pwsh

      # - name: Publish Module
      #   shell: pwsh
      #   run: Publish-Module -Path quickpath -NuGetApiKey ${{ secrets.NUGET_API_KEY }}
