name: Publish Module

on:
  release
    
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set working directory to root of repository
        run: echo "{name}={value}" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: Install Invoke-Build
        shell: pwsh
        run: Install-Module -Name InvokeBuild -Scope CurrentUser -Force

      - name: Publish Module
        shell: pwsh
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: Invoke-Build Publish
