name: Publish Module

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract release tag
        id: tag
        run: echo "::set-output name=RELEASE_TAG::${GITHUB_REF##*/}"

      - name: Override module version
        run: |
          $tag = "${{ steps.tag.outputs.RELEASE_TAG }}"
          (Get-Content -Path 'quickpath.psd1') -replace 'Version = ''[0-9\.]+''', "Version = '$tag'" | Set-Content -Path 'quickpath.psd1'
        

      # - name: Set working directory to root of repository
      #   run: echo "{name}={value}" >> $GITHUB_OUTPUT
      #   shell: bash
      
      # - name: Install Invoke-Build
      #   shell: pwsh
      #   run: Install-Module -Name InvokeBuild -Scope CurrentUser -Force

      # - name: Publish Module
      #   shell: pwsh
      #   run: Publish-Module -Path quickpath -NuGetApiKey ${{ secrets.NUGET_API_KEY }}
