name: Publish Module

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          name: quickpath
          search_artifacts: true
          branch: main

      - name: Extract package
        shell: pwsh
        run: Expand-Archive -Path quickpath.zip -DestinationPath .

      - name: list files
        run: ls -R

      - name: Override module version
        run: |
          $TAG_VERSION="${GITHUB_REF##*/}"
          $MODULE_VERSION="${TAG_VERSION#v}"
          (Get-Content 'quickpath/quickpath.psd1') -replace "ModuleVersion\s*=\s*'[^']+'", "ModuleVersion = '$MODULE_VERSION'" | Set-Content 'quickpath/quickpath.psd1'
        shell: pwsh

      - name: list files
        run: ls -R

      - name: Get manifest module version
        shell: pwsh
        run: (Get-Content -Path 'quickpath/quickpath.psd1' )

      - name: Publish Module
        shell: pwsh
        run: Publish-Module -Path quickpath -NuGetApiKey ${{ secrets.NUGET_API_KEY }}
